# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(username: 'sepadmin2014', email:  'sepadmin2014@gmail.com ', password: "sepadmin2014", password_confirmation: "sepadmin2014")
Tipodoc.create(sigla: "CC", descripcion: "Cedula Ciudadania")
Tipodoc.create(sigla: "T.I", descripcion: "Tarjeta Identidad")
Categoria.create(nombre: "Soporte Tecnico". descripcion: "Soporte Tecnico")
Categoria.create(nombre: "Desarrollo BD". descripcion: "Desarrollo BD")
Categoria.create(nombre: "Analista de sistemas". descripcion: "Analista de sistemas")
Categoria.create(nombre: "Desarrollo Aplicativo". descripcion: "Desarrollo Aplicativo")
Categoria.create(nombre: "Documentación De Proyectos". descripcion: "Documentación De Proyectos")
Categoria.create(nombre: "Capacitación". descripcion: "Capacitación")
Titulacion.create(sigla: "T.G", descripcion: "Tecnologos")
Titulacion.create(sigla: "T.C", descripcion: "Tecnicos")
Area.create(nombre: "Sistemas", sigla:"Sistemas")
Area.create(nombre: "Gestion Humana", sigla:"Gestion Humana")
Centro.create(nombre: "Centro de Formación en Diseño, Confección y Moda", direccion: "Calle 63 N° 58B - 03 Itaguí- Calatrava" codigo: "1")
Actestado.create(nombre: "Enproceso", descripcion: "Enproceso")
Actestado.create(nombre: "Pendiente", descripcion: "Pendiente")
Actestado.create(nombre: "Culminación", descripcion: "Culminación")
Actestado.create(nombre: "Terminado", descripcion: "Terminado")
Tipopractica.create(nombre: "Contrato de Aprendizaje", descripcion: "Contrato de Aprendizaje")
Tipopractica.create(nombre: "Vinculación Laboral o Contractual", descripcion: "Vinculación Laboral o Contractual")
Tipopractica.create(nombre: "Participación en un Proyecto Productivo en SENA, Empresa, en SENA Proveedor o en Producción de Centros", descripcion: "Participación en un Proyecto Productivo en SENA, Empresa, en SENA Proveedor o en Producción de Centros")
Tipopractica.create(nombre: "Apoyo a una unidad productiva familiar", descripcion: "Apoyo a una unidad productiva familiar")
Tipopractica.create(nombre: "Monitorias", descripcion: "Monitorias")
Tipopractica.create(nombre: "Apoyo a una institución estatal, nacional, territorial, a una ONG o a una entidad sin ánimo de lucro", descripcion: "Apoyo a una institución estatal, nacional, territorial, a una ONG o a una entidad sin ánimo de lucro")
Tipopractica.create(nombre: " 	Pasantías", descripcion: " 	Pasantías")
Ficha.create(numero: "323921", fecha_inicio_practicas: "2013-10-10", programa_id: "1", fecha_fin_practicas: " 	2014-04-09" )
Empresa.create(nombre: "SENA", nit: "899999034-9", dv: "1", direccion: "Calle 63 #53b-03 calatraba", telefono: "5149294", fax: "3717896", email: "william.betancur@misena.edu.co", paginaweb: "www.sena.edu.co")
Empresa.create(nombre: "Personalsoft S.A.S", nit: "811.022.382-5", dv: "5", direccion: "Cra. 65 N° 48 - 162", telefono: "403 7250 	", fax: "434 0657", email: "contactenos@personalsoft.com.co", paginaweb: "www.personalsoft.com")
Empresa.create(nombre: "RISKS AND PROTECTION", nit: "900171792", dv: "-2", direccion: "CRR 43B #32 SUR 17", telefono: "4481112", fax: "4481112", email: " 	servicioalcliente@risksprotection.com", paginaweb: "www.risksprotectio.com")
Empresa.create(nombre: "Topasa", nit: "823.034.991", dv: "1", direccion: "Carrea 62 sur .44-43", telefono: "3200180", fax: "2882364", email: "ghumana@topasa.com", paginaweb: "www.topasa.com")
Empresa.create(nombre: "Tuya S.A", nit: "860032330", dv: "1", direccion: " 	cll 4 sur # 43 a 109", telefono: "3198210", fax: "3526275", email: "reclutamiento@tarjetaexito.com.co", paginaweb: "www.tuya.com.co")
Empresa.create(nombre: " Alimentos C. S.A.S", nit: "890304130-4", dv: "1", direccion: "", telefono: "", fax: "", email: "", paginaweb: "")
